const constants = {
	// ADD_DAY: "ADD_DAY",
	// REMOVE_DAY: "REMOVE_DAY",
	// SET_GOAL: "SET_GOAL",
	// ADD_ERROR: "ADD_ERROR",
	// CLEAR_ERROR: "CLEAR_ERROR",
	// FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
	// CANCEL_FETCHING: "CANCEL_FETCHING",
	// CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    // CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
    RUN_STOP: "RUN_STOP",
    UPDATE_BOARD: "UPDATE_BOARD",
	UPDATE_SIZE: "UPDATE_SIZE",
	UPDATE_SCORE: "UPDATE_SCORE",
	UPDATE_TIMER: "UPDATE_TIMER",
	TOGGLE_TORUS: "TOGGLE_TORUS",
	SAVE_PATTERN: "SAVE_PATTERN",
	DELETE_PATTERN: "DELETE_PATTERN",
	SELECT_PATTERN: "SELECT_PATTERN"
}

export default constants